### ISSUE TITLE
Duplicate "Filters applied"  in Version 1.1.3

### ISSUE THREAD

**Issue by FredRDewitt** [travelpayouts/travel-app-android#27]
![Screenshot_1568382047](https://user-images.githubusercontent.com/45330656/64867121-a700c600-d634-11e9-8daa-fe34f5a53e56.png)

**Comment by RoberMS** [comment]
- Same bug, duplicate "Filters applied".
- Also the search hotel button now shows "The best hotel deals", can you put "Find hotels" as it was before?
- If possible, also remove the title from the hotel search box, or put it in the flight search box, so that both are equals.
- In the flight search box when clicking on select passengers, the color is not applied to the buttons, however in the hotel search box when selecting guests if you apply the color correctly

**Comment by vlshevtsov** [comment]
We have fixed the issue in the current version 1.1.6.
