### ISSUE TITLE
Where is strings?

### ISSUE THREAD

**Issue by maxuna14** [travelpayouts/travel-app-android#8]
Hello,
Where does the strings come from? where strings file is located? Georgian translation not, I want to translate it. please reply where is strings file, app/src/res/values/strings.xml only few strings.

**Comment by b1uebyte** [comment]
@maxuna14 there is no easy way to provide your custom translation at the moment. We support only `ru` and `en` locales. We will add more soon but the bad news is that `ka`-locale is not in our nearest plans.

**Comment by maxuna14** [comment]
Upload strings in Crowdin and I will done in 2 days.

**Comment by maxuna14** [comment]
or just sent me in Email. I will help you. I did all White label and widgets translations to KA.

**Comment by b1uebyte** [comment]
@maxuna14 for now we can't add your translation to our sources, but we can give you a way how you can override strings for Georgian locale by yourself.

1. Create `values-ka` folder in `app/src/main/res`
2. Create file `strings.xml`
3. Add translated strings

The hard thing is how to find keys for strings. This are all strings which are used in project. The problem is that you don't need most of them.
[values.xml.zip](https://github.com/travelpayouts/travel-app-android/files/3460907/values.xml.zip)

Try with one string and let me know if it works for you.

**Comment by maxuna14** [comment]
Thank you, I am find it already 3 days ago, half of them strings translated.

Thank you

**Comment by maxuna14** [comment]
>  The problem is that you don't need most of them
I translating only strings where is used in App. Run and look every page where is missing translation I searching strings, translating.

**Comment by Musacca** [comment]
Did you find string file for hotels?
